### ISSUE TITLE
Build Fails "a as array"

### ISSUE THREAD

**Issue by rishisubramanian** [Aaronepower/tokei#291]
I'm trying to build from source, but the build fails with the following backtrace:
```
rishi@rishi-desktop ~/P/tokei (master)> env RUST_BACKTRACE=1 cargo build --release
   Compiling tokei v9.0.0 (/home/rishi/Programs/tokei)
error: failed to run custom build command for `tokei v9.0.0 (/home/rishi/Programs/tokei)`
process didn't exit successfully: `/home/rishi/Programs/tokei/target/release/build/tokei-da77eb51f2b15128/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'a as array', libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::option::expect_failed
             at libcore/option.rs:1008
   9: build_script_build::compare_json_str_len
  10: core::slice::sort::recurse
  11: build_script_build::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  16: main
  17: __libc_start_main
  18: _start
```

I'm using the latest stable Rustc (1.31.1) and Cargo on Arch Linux.

**Comment by Aaronepower** [comment]
@rishisubramanian Thank you for your issue! I can not replicate this issue on Arch or any other platform. From looking at the error I would guess that the `languages.json` has been modified. Are you sure you're working from a clean version?

**Comment by rishisubramanian** [comment]
I was actually trying to add a language. Was I supposed to modify something other than languages,json?

**Comment by Aaronepower** [comment]
@rishisubramanian It sounds like you have a leading comma where you're not supposed to. Youy can use something like https://jsonchecker.com/ to check that syntax is correct.

**Comment by rishisubramanian** [comment]
I checked it using the provided link, as well as Python's JSON parser. Both said it's valid. 

Alternatively, is there a way to add languages in the tokeirc file?

**Comment by Aaronepower** [comment]
There is no a way to dynamically add languages at runtime, and I'm not currently sure if there will be. Could you paste the diff of the JSON you tried to add?

**Comment by rishisubramanian** [comment]
```
"MATLAB":{
            "extensions": ["m"],
            "line_comment": ["%"],
            "multi_line": ["%{", "%}"],
            "quotes": [
                ["'", "'"],
                ["\\\"", "\\\""]
            ]
        },

```

**Comment by Aaronepower** [comment]
Where did you attempt to put this in the file?

**Comment by Aaronepower** [comment]
I'm going to close this issue as there doesn't seem to be anything wrong with tokei itself. Please do continue to show how you got this error and I can help you make a pull request to add Matlab to tokei.
